# Setup
title:	      Yan's homepage
tagline:      An astronomer
baseurl:      ""
paginate:     1

# About/contact
author:       Yan
  name:       Yan
  url:        http://www.pmo.ac.cn

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
