# Setup
title:	      Yan Gong's homepage
tagline:      An astronomer
baseurl:      ""
paginate:     1

# About/contact
author:       Yan Gong
  name:       Yan Gong
  url:        http://www.pmo.ac.cn

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
